### ISSUE TITLE
docker installation does not copy all of the files

### ISSUE THREAD

**Issue by DavidBilodeau1** [algirdasc/expensave#130]
When installing on a docker compose stack (or creating the docker container from portainer), the ui files are not copied in /public/ui which then creates a 500 error when trying to access the web page.
![image](https://github.com/user-attachments/assets/11b75bb3-b88f-4741-902c-e00ca4a0facd)

**Comment by DavidBilodeau1** [comment]
using version v0.1.0 fixed the issue, it might have been introduced in v0.1.2-docker-fix

**Comment by algirdasc** [comment]
There was a building image problem after upgrading to Angular 18, because it changed paths. Pushed new release which fixed this issue. Let me know if it solves this problem.

**Comment by DavidBilodeau1** [comment]
@algirdasc it does fix the issue, thank you!
