### ISSUE TITLE
unable to register or login on local docker install

### ISSUE THREAD

**Issue by DavidBilodeau1** [algirdasc/expensave#131]
Error 504 when trying to register or login in a local docker install
![image](https://github.com/user-attachments/assets/c6738d30-e39b-4ca6-a4a6-410045318e01)
![image](https://github.com/user-attachments/assets/e8eee7b6-eb4f-4858-8f4b-391645d9d625)

**Comment by DavidBilodeau1** [comment]
same thing, was introduced in v0.1.2-docker-fix, not present in v0.1.0

**Comment by algirdasc** [comment]
Tested with newest release fresh install - could not reproduce this problem. Could you try to update to latest version?
